#!/bin/sh
# postinst script for mate-wp
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
        xdg-desktop-menu install /opt/mate-wp/lib/mate-wp-mate-wp.desktop
        ln -sf /opt/mate-wp/bin/mate-wp /usr/bin/mate-wp
        ln -sf /opt/mate-wp/lib/app/mate-wp-update.sh /etc/cron.daily/mate-wp-update
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        # do nothing
    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0