package ee.mcdimus.matewp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 *
 * @author Dmitri Maksimov
 */
public class PropUtil {

//    private static final Logger log = LoggerFactory.getLogger(PropUtil.class);
  /**
   * Properties file should be generated by ant.
   */
  private static final String CONFIG_FILENAME = "config.properties";
  private static Properties properties;

  private PropUtil() {
  }

  private static void init() {
        // use this if file is in the classpath
//    try (InputStream input = PropUtil.class.getClassLoader().getResourceAsStream(CONFIG_FILENAME)) {
    // use this if file is in jar's directory
    String configFileLocation = new File(PropUtil.class.getProtectionDomain().getCodeSource().getLocation().getPath()).getParentFile().getPath();

    try (InputStream input = new FileInputStream(configFileLocation + File.separator + CONFIG_FILENAME)) {
      if (input == null) {
        throw new FileNotFoundException();
      }
      Properties p = new Properties();

      p.load(input);
      properties = p;
    } catch (IOException ex) {
      System.exit(1);
    }
  }

  private static Properties getProperties() {
    if (properties == null) {
      init();
    }
    return properties;
  }

}
